name: pygmt06
channels:
  - conda-forge
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.10.0
  - bleach=4.1.0
  - blosc=1.21.0
  - boost-cpp=1.74.0
  - branca=0.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.1.0
  - cftime=1.6.0
  - charset-normalizer=2.0.12
  - click=8.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - cryptography=36.0.2
  - curl=7.82.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.8
  - fftw=3.3.10
  - fiona=1.8.21
  - flit-core=3.7.1
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.31.2
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.4.2
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geos=3.10.2
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - ghostscript=9.54.0
  - gmt=6.3.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.6.0
  - intel-openmp=2022.0.0
  - ipykernel=6.11.0
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.1
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.1
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyter_server=1.16.0
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=1.1.0
  - kealib=1.4.14
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.82.0
  - libdeflate=1.10
  - libffi=3.4.2
  - libgdal=3.4.2
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=14.2
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - munkres=1.1.4
  - nbclassic=0.3.7
  - nbclient=0.5.13
  - nbconvert=6.4.5
  - nbconvert-core=6.4.5
  - nbconvert-pandoc=6.4.5
  - nbformat=5.2.0
  - nest-asyncio=1.5.4
  - netcdf4=1.5.8
  - networkx=2.7.1
  - notebook=6.4.10
  - notebook-shim=0.1.0
  - numpy=1.22.3
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.2
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.0.4
  - pixman=0.40.0
  - poppler=22.01.0
  - poppler-data=0.4.11
  - postgresql=14.2
  - proj=9.0.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.27
  - prompt_toolkit=3.0.27
  - psutil=5.9.0
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pygmt=0.6.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyproj=3.3.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.1
  - pywin32=303
  - pywinpty=2.0.5
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.3.0
  - qtconsole-base=5.3.0
  - qtpy=2.0.1
  - requests=2.27.1
  - rtree=0.9.7
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - send2trash=1.8.0
  - setuptools=61.3.1
  - shapely=1.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.37.1
  - stack_data=0.2.0
  - tbb=2021.5.0
  - terminado=0.13.3
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tiledb=2.7.2
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xarray=2022.3.0
  - xerces-c=3.2.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.3.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
